name: Update subscription

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # هر روز ساعت ۰۰:۰۰ UTC
  workflow_dispatch:

jobs:
  update-subscription:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run main.py
        run: python main.py

      - name: Commit and push changes if any
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add docs/subscription.txt

          # قبل از commit حتما pull --rebase کن تا تداخل نگیره
          git pull --rebase --autostash origin main

          # اگر چیزی تغییر نکرد، commit نمی‌کنه
          git diff --cached --quiet && echo "No changes to commit" || (
            git commit -m "Auto update subscription [skip ci]"
            git push origin main
          )
