name: Update Subscription Daily

on:
  schedule:
    - cron: "0 0 * * *"   # هر روز ساعت ۰۰:۰۰ UTC اجرا می‌شود
  workflow_dispatch:       # امکان اجرای دستی از تب Actions

permissions:
  contents: write          # ⚡️ اجازه Push تغییرات به ریپو

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Python script
        run: python main.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add subscription.txt
          git commit -m "Auto update subscription [skip ci]" || echo "No changes to commit"
          git push origin HEAD:main
