name: Update subscription

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # هر روز ساعت 00:00 UTC
  workflow_dispatch:

jobs:
  update-subscription:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install requests
        run: pip install requests

      - name: Run main.py
        run: python main.py

      - name: Commit subscription update
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/subscription.txt
          git commit -m "Auto update subscription [skip ci]" || echo "No changes to commit"
          git push
